# Generated by Django 3.0.2 on 2020-01-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noc',
            name='notes',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='Notes about NOC or Country.'),
        ),
    ]
