# Generated by Django 3.0.2 on 2020-01-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
