# Generated by Django 3.0.2 on 2020-01-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0002_auto_20200117_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='athlete',
            name='athlete_id',
            field=models.IntegerField(verbose_name='Athlete ID'),
        ),
    ]
