# Generated by Django 3.0.2 on 2020-01-18 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0004_auto_20200118_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='noc',
            field=models.ForeignKey(db_column='noc', on_delete=django.db.models.deletion.CASCADE, to='olympic.NOC'),
        ),
    ]
